# fly.toml app configuration file generated for meos-7tup-a on 2025-10-23T20:35:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meos-7tup-a'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
